"""Generates a dynamic Markdown report aggregating all analytical figures and tables.

Produces outputs/final_report.md automatically pulling from the generated plots and CSV summaries.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import pandas as pd


def generate_report(results_path: Path, summary_path: Path, plots_dir: Path, out_path: Path) -> None:
    lines = []
    lines.append("# Causal Discovery Framework: Comprehensive Analysis Report\n")
    lines.append("> Auto-generated by the Experimental Automation Pipeline.\n")

    lines.append("## Overview")
    lines.append("This report dynamically aggregates the benchmark metrics across the massive evaluated combinatorial grid of data generation processes. ")
    lines.append("Algorithms were evaluated across structural metrics (F1, Precision, Recall, SHD, Orientation Accuracy) and parameter sensitivities.\n")

    # Load Data
    if not results_path.exists() or not summary_path.exists():
        lines.append("\n**WARNING**: Could not find master CSV or summary CSV data. Analytics table will be missing.\n")
    else:
        df = pd.read_csv(results_path)
        sum_df = pd.read_csv(summary_path)
        
        total_exps = df["exp_dir_name"].nunique() if "exp_dir_name" in df.columns else "N/A"
        lines.append(f"- **Total distinct data generation configurations tested**: {total_exps}")
        lines.append(f"- **Total algorithm runs evaluated**: {len(df)}\n")

        lines.append("### Global Top Performers (Best F1 Score without postprocessing)")
        try:
            # Filter non-postprocessed and grab best mean F1 per algo
            non_post = sum_df[sum_df["postprocessed"] == False] if "postprocessed" in sum_df.columns else sum_df
            best_algos = non_post.groupby("algorithm")["f1_mean"].mean().reset_index().sort_values(by="f1_mean", ascending=False)
            
            lines.append(best_algos.to_markdown(index=False, floatfmt=".3f"))
            lines.append("\n")
        except Exception as e:
            lines.append(f"*Could not generate top performers table: {e}*\n")

    # Section A
    lines.append("## A. Algorithm Comparison")
    lines.append("We compare the algorithms directly on their structural recovery scores (F1, SHD) and execution runtime.\n")
    if (plots_dir / "algo_comparison_f1.png").exists():
        lines.append("![F1 Comparison](../analysis_plots/algo_comparison_f1.png)\n")
    if (plots_dir / "algo_comparison_shd.png").exists():
        lines.append("![SHD Comparison](../analysis_plots/algo_comparison_shd.png)\n")
    if (plots_dir / "algo_comparison_runtime_sec.png").exists():
        lines.append("![Runtime Comparison](../analysis_plots/algo_comparison_runtime_sec.png)\n")

    # Section B
    lines.append("## B. Sensitivity Analysis")
    lines.append("How does robustness hold as environments become mathematically adversarial (shorter lengths, larger dimensions, harder noise)?\n")
    if (plots_dir / "sensitivity_sample_length.png").exists():
        lines.append("![Sample Length Impact](../analysis_plots/sensitivity_sample_length.png)\n")
    if (plots_dir / "sensitivity_graph_size.png").exists():
        lines.append("![Graph Size Impact](../analysis_plots/sensitivity_graph_size.png)\n")
    if (plots_dir / "sensitivity_heatmap_noise_nonlinear.png").exists():
        lines.append("![Noise vs Nonlinearity](../analysis_plots/sensitivity_heatmap_noise_nonlinear.png)\n")

    # Section C
    lines.append("## C. Structural Causal Model (SCM) Base Impact")
    lines.append("Evaluates whether the internally standardized SCM (iSCM) fixes variance-ordering artifacts relative to the classical SCM across algorithms.\n")
    if (plots_dir / "scm_comparison_f1.png").exists():
        lines.append("![Classical vs ISCM](../analysis_plots/scm_comparison_f1.png)\n")

    # Section D
    lines.append("## D. Failure Modes")
    lines.append("Where do standard discovery algorithms fail completely? We break down performance drops across underlying graph topologies (Hub, Chain, Cycle, Random).\n")
    if (plots_dir / "failure_graph_types.png").exists():
        lines.append("![Graph Topologies](../analysis_plots/failure_graph_types.png)\n")
        
    lines.append("### Cycle Topology: The Feedback Strength Problem")
    lines.append("For true cyclic temporal graphs, algorithms usually struggle based on the intensity of the autoregressive feedback loop. The plot below traces F1 degradation across feedback sizes.\n")
    if (plots_dir / "failure_cycles_feedback.png").exists():
        lines.append("![Cycles Feedback Impact](../analysis_plots/failure_cycles_feedback.png)\n")

    lines.append("\n---\n*End of Report*\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate final markdown report.")
    parser.add_argument("--results-csv", type=str, default="outputs/grid_search/master_results.csv")
    parser.add_argument("--summary-csv", type=str, default="outputs/grid_search/master_summary.csv")
    parser.add_argument("--plots-dir", type=str, default="outputs/analysis_plots")
    parser.add_argument("--out-md", type=str, default="outputs/final_report.md")
    args = parser.parse_args()

    results_csv = Path(args.results_csv)
    summary_csv = Path(args.summary_csv)
    plots_dir = Path(args.plots_dir)
    out_md = Path(args.out_md)

    print(f"Generating markdown report at {out_md}...")
    generate_report(results_csv, summary_csv, plots_dir, out_md)
    print("Done!")


if __name__ == "__main__":
    main()
